// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "description": "Authenticate with email and password, receive JWT tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in with credentials",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/refresh": {
            "post": {
                "description": "Exchange a valid refresh token for a new token pair",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.TokenResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "description": "Create a new user account with email, password, first name and last name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/deliveries/assign": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manual assignment (provide courier_id) or auto-assignment (leave courier_id empty, system finds nearest in zone via PostGIS)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deliveries"
                ],
                "summary": "Assign courier to delivery",
                "parameters": [
                    {
                        "description": "Assignment request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.AssignCourierSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.AssignCourierSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/deliveries/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve delivery details including courier, status and ETA",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deliveries"
                ],
                "summary": "Get delivery by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delivery ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.GetDeliverySwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/notifications/send": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Send a notification to a user using a template. Normally triggered by Kafka events, but can be called directly.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Send a notification",
                "parameters": [
                    {
                        "description": "Notification request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.SendNotificationSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.SendNotificationSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/notifications/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve notification details by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Get notification by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.GetNotificationSwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a list of orders for the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "List orders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (e.g. ORDER_STATUS_CREATED)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ListOrdersSwaggerResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a delivery order with address, coordinates, items and payment method",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Create a new order",
                "parameters": [
                    {
                        "description": "Order data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.CreateOrderSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.CreateOrderSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/orders/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve order details by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Get order by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.GetOrderSwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/orders/{id}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cancel an eligible order with an optional reason",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Cancel an order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancel reason",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.CancelOrderSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.CancelOrderSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/orders/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transition order to a new status following the state machine rules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Update order status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.UpdateOrderStatusSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.UpdateOrderStatusSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid status transition",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/zones": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all delivery zones",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "List delivery zones",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ListZonesSwaggerResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new delivery zone with a GeoJSON polygon boundary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "Create delivery zone",
                "parameters": [
                    {
                        "description": "Zone definition",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.CreateZoneSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.CreateZoneSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/zones/assign-courier": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Assign a courier to operate in a specific delivery zone",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "Assign courier to zone",
                "parameters": [
                    {
                        "description": "Assignment",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.AssignCourierToZoneSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.AssignCourierToZoneSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services_api-gateway_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "services_api-gateway_internal_handler_http.AssignCourierSwaggerRequest": {
            "type": "object",
            "properties": {
                "courierId": {
                    "type": "string",
                    "example": "770e8400-e29b-41d4-a716-446655440000"
                },
                "orderId": {
                    "type": "string",
                    "example": "660e8400-e29b-41d4-a716-446655440000"
                },
                "zoneId": {
                    "type": "string",
                    "example": "880e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "services_api-gateway_internal_handler_http.AssignCourierSwaggerResponse": {
            "type": "object",
            "properties": {
                "delivery": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.DeliveryModel"
                }
            }
        },
        "services_api-gateway_internal_handler_http.AssignCourierToZoneSwaggerRequest": {
            "type": "object",
            "properties": {
                "courierId": {
                    "type": "string",
                    "example": "770e8400-e29b-41d4-a716-446655440000"
                },
                "zoneId": {
                    "type": "string",
                    "example": "880e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "services_api-gateway_internal_handler_http.AssignCourierToZoneSwaggerResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "services_api-gateway_internal_handler_http.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "user": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.UserInfo"
                }
            }
        },
        "services_api-gateway_internal_handler_http.CancelOrderSwaggerRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string",
                    "example": "Передумал"
                }
            }
        },
        "services_api-gateway_internal_handler_http.CancelOrderSwaggerResponse": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.OrderModel"
                }
            }
        },
        "services_api-gateway_internal_handler_http.CoordinatesModel": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": 55.7558
                },
                "longitude": {
                    "type": "number",
                    "example": 37.6173
                }
            }
        },
        "services_api-gateway_internal_handler_http.CreateOrderSwaggerRequest": {
            "type": "object",
            "properties": {
                "contact_phone": {
                    "type": "string",
                    "example": "+79001234567"
                },
                "delivery_address": {
                    "type": "string",
                    "example": "ул. Пушкина 10, Москва"
                },
                "delivery_coordinates": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.CoordinatesModel"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services_api-gateway_internal_handler_http.OrderItemModel"
                    }
                },
                "payment_method": {
                    "type": "string",
                    "example": "card"
                }
            }
        },
        "services_api-gateway_internal_handler_http.CreateOrderSwaggerResponse": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.OrderModel"
                }
            }
        },
        "services_api-gateway_internal_handler_http.CreateZoneSwaggerRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Центральная Москва"
                },
                "polygonGeojson": {
                    "type": "string",
                    "example": "{\"type\":\"Polygon\",\"coordinates\":[[[37.5,55.7],[37.7,55.7],[37.7,55.8],[37.5,55.8],[37.5,55.7]]]}"
                }
            }
        },
        "services_api-gateway_internal_handler_http.CreateZoneSwaggerResponse": {
            "type": "object",
            "properties": {
                "zone": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.DeliveryZoneModel"
                }
            }
        },
        "services_api-gateway_internal_handler_http.DeliveryModel": {
            "type": "object",
            "properties": {
                "courierId": {
                    "type": "string",
                    "example": "770e8400-e29b-41d4-a716-446655440000"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2026-03-29T10:00:00Z"
                },
                "estimatedDelivery": {
                    "type": "string",
                    "example": "2026-03-29T12:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "orderId": {
                    "type": "string",
                    "example": "660e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "DELIVERY_STATUS_ASSIGNED"
                },
                "zoneId": {
                    "type": "string",
                    "example": "880e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "services_api-gateway_internal_handler_http.DeliveryZoneModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "880e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Центральная Москва"
                },
                "polygonGeojson": {
                    "type": "string",
                    "example": "{\"type\":\"Polygon\",\"coordinates\":[[[37.5,55.7],[37.7,55.7],[37.7,55.8],[37.5,55.8],[37.5,55.7]]]}"
                }
            }
        },
        "services_api-gateway_internal_handler_http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid input"
                }
            }
        },
        "services_api-gateway_internal_handler_http.GetDeliverySwaggerResponse": {
            "type": "object",
            "properties": {
                "delivery": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.DeliveryModel"
                }
            }
        },
        "services_api-gateway_internal_handler_http.GetNotificationSwaggerResponse": {
            "type": "object",
            "properties": {
                "notification": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.NotificationModel"
                }
            }
        },
        "services_api-gateway_internal_handler_http.GetOrderSwaggerResponse": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.OrderModel"
                }
            }
        },
        "services_api-gateway_internal_handler_http.ListOrdersSwaggerResponse": {
            "type": "object",
            "properties": {
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services_api-gateway_internal_handler_http.OrderModel"
                    }
                }
            }
        },
        "services_api-gateway_internal_handler_http.ListZonesSwaggerResponse": {
            "type": "object",
            "properties": {
                "zones": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services_api-gateway_internal_handler_http.DeliveryZoneModel"
                    }
                }
            }
        },
        "services_api-gateway_internal_handler_http.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "mypassword123"
                }
            }
        },
        "services_api-gateway_internal_handler_http.NotificationModel": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string",
                    "example": "email"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2026-03-29T10:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "990e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "NOTIFICATION_STATUS_SENT"
                },
                "templateName": {
                    "type": "string",
                    "example": "order_confirmed"
                },
                "templateVars": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "order_id": "123",
                        "status": "confirmed"
                    }
                },
                "userId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "services_api-gateway_internal_handler_http.OrderItemModel": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Pizza Margherita"
                },
                "price": {
                    "type": "number",
                    "example": 500
                },
                "quantity": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "services_api-gateway_internal_handler_http.OrderModel": {
            "type": "object",
            "properties": {
                "contactPhone": {
                    "type": "string",
                    "example": "+79001234567"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2026-03-29T10:00:00Z"
                },
                "deliveryAddress": {
                    "type": "string",
                    "example": "ул. Пушкина 10, Москва"
                },
                "deliveryCoordinates": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.CoordinatesModel"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services_api-gateway_internal_handler_http.OrderItemModel"
                    }
                },
                "paymentMethod": {
                    "type": "string",
                    "example": "card"
                },
                "status": {
                    "type": "string",
                    "example": "ORDER_STATUS_CREATED"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2026-03-29T10:00:00Z"
                },
                "userId": {
                    "type": "string",
                    "example": "660e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "services_api-gateway_internal_handler_http.RefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "services_api-gateway_internal_handler_http.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Никита"
                },
                "last_name": {
                    "type": "string",
                    "example": "Мозговой"
                },
                "password": {
                    "type": "string",
                    "example": "mypassword123"
                }
            }
        },
        "services_api-gateway_internal_handler_http.SendNotificationSwaggerRequest": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string",
                    "example": "email"
                },
                "templateName": {
                    "type": "string",
                    "example": "order_confirmed"
                },
                "templateVars": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "userId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "services_api-gateway_internal_handler_http.SendNotificationSwaggerResponse": {
            "type": "object",
            "properties": {
                "notification": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.NotificationModel"
                }
            }
        },
        "services_api-gateway_internal_handler_http.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "services_api-gateway_internal_handler_http.UpdateOrderStatusSwaggerRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ORDER_STATUS_CONFIRMED"
                }
            }
        },
        "services_api-gateway_internal_handler_http.UpdateOrderStatusSwaggerResponse": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/services_api-gateway_internal_handler_http.OrderModel"
                }
            }
        },
        "services_api-gateway_internal_handler_http.UserInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Никита"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "last_name": {
                    "type": "string",
                    "example": "Мозговой"
                },
                "role": {
                    "type": "string",
                    "example": "user"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Delivery Tracker API",
	Description:      "REST API for the Delivery Tracker microservice platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
